environment:
  myuser:
    secure: BNlXevLtF9e2aPA67RkRlg==
  mypass:
    secure: UVcVBPUuJmH6Dargd2JZHitYoqNavVuBWWeJ8fvarLfSahvVhAAlXsnO2roo/75L
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\ci\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Miniconda"
      CONDA_PY: "27"

    - PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"
      ARCH: "64"

    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "34"

    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "34"
      ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;"

  - conda update --yes conda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION
  - conda install --yes pip numpy scipy six pandas
  - conda install --yes theano scikit-learn nose
  # installing self
  - pip install . --no-dependencies

build: false # Not a C# project, build stuff at the test step instead.

test_script:
  # run testsuite and upload test results to AppVeyor; return exit code of testsuite
  - nosetests tests