language: python

matrix:
    include:
        - os: linux
          python: '2.7'
        - os: linux
          python: '3.4'
        - os: osx
          python: '2.7'
        - os: osx
          python: '3.4'

before_install:
  - travis_retry pip install numpy scipy six pandas -q
  - travis_retry pip install scikit-learn nose -q
  - travis_retry pip install theano -q
install:
  - travis_retry pip install . --no-dependencies
script: nosetests tests
cache:
  - directories:
    - $HOME/.cache/pip