language: python
sudo: false
addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libblas-dev
      - liblapack-dev
      - python-numpy
      - python-scipy
      - python-matplotlib
      - python-pandas
      - python-nose
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests tests