language: python
sudo: false
addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests tests