language: python

matrix:
    include:
        - os: linux
          python: '2.7'
        - os: linux
          python: '3.4'
        - os: osx
          language: generic
          before_install:
            - brew update
            - virtualenv env -p python2
            - source env/bin/activate
        - os: osx
          language: generic
          before_install:
            - brew update
            - brew install python3
            - virtualenv env -p python3
            - source env/bin/activate

install:
  - pip install pip --upgrade -q
  - travis_retry pip install numpy scipy six pandas -q
  - travis_retry pip install scikit-learn nose -q
  - travis_retry pip install .
script: nosetests tests
