language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas3gf-base libatlas-dev python-scipy
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests tests