language: python

matrix:
    include:
        - os: linux
          python: '2.7'
        - os: linux
          python: '3.6'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libopenblas-dev
install:
  - pip install pip --upgrade -q
  - travis_retry pip install numpy scipy six pandas -q
  - travis_retry pip install scikit-learn nose -q
  - travis_retry pip install .
script: nosetests tests
